<script setup lang="ts">
import meta from '../../../../meta'

const { public: { siteUrl } } = useRuntimeConfig()
const pageUrl = `${siteUrl}/tools/qr-code-generator/wifi`

useSeoMeta({
  title: 'WiFi QR Code Generator — Share Your Network Without Typing Passwords',
  description: 'Create a WiFi QR code guests can scan to connect instantly. WPA/WPA2/WPA3, WEP and open networks. Free, no sign-up, generated in your browser — the password never leaves your device.',
  ogTitle: 'WiFi QR Code Generator — free, no sign-up',
  ogDescription: 'Let guests scan to join your WiFi. The password never leaves your browser.',
  ogUrl: pageUrl,
  twitterCard: 'summary_large_image',
})

defineOgImage('Default', {
  title: 'WiFi QR Code Generator',
  description: 'Let guests scan to join your WiFi. The password never leaves your browser.',
})

useToolJsonLd(meta, { variant: 'wifi' })

const { track } = useAnalytics()
onMounted(() => track('tool_viewed', { tool: 'qr-code-generator' }))

const faq = [
  { q: 'How do guests use a WiFi QR code?', a: 'They point their phone camera at it. iOS and Android both recognize WiFi QR codes natively and show a "Join network" prompt — no app needed, no password typed.' },
  { q: 'Is it safe to put my WiFi password in a QR code?', a: 'The code is generated entirely in your browser; the password is never sent to us and is never included in shareable links. Anyone who can physically scan the printed code can join the network — treat the printout like you would treat the password itself.' },
  { q: 'Which security type should I pick?', a: 'WPA covers WPA2 and WPA3, which is almost every modern router. Only pick WEP for very old hardware, or Open for password-less guest networks.' },
  { q: 'My network is hidden — will the QR code work?', a: 'Yes. Tick "Hidden network" and the code includes the flag scanners need to find an SSID that is not broadcasting.' },
]
</script>

<template>
  <div class="container-page py-10">
    <ToolPageHeader
      title="WiFi QR Code Generator"
      description="Print it, frame it, tape it to the fridge — guests scan and connect. Your password never leaves this browser tab."
    />

    <ClientOnly>
      <QrTool initial-tab="wifi" />
      <template #fallback>
        <div class="grid h-96 place-items-center rounded-2xl border border-neutral-200 text-sm text-neutral-400 dark:border-neutral-800">
          Loading the generator…
        </div>
      </template>
    </ClientOnly>

    <div class="mx-auto mt-16 space-y-12">
      <section aria-labelledby="wifi-howto" class="rounded-2xl bg-muted/50 p-6 sm:p-8">
        <h2 id="wifi-howto" class="text-xl font-semibold">
          Sharing WiFi the civilized way
        </h2>
        <div class="mt-4 space-y-4 text-sm leading-relaxed text-neutral-700 dark:text-neutral-300">
          <p>
            Reading a 16-character password off the back of a router is nobody's idea of hospitality. A WiFi QR code encodes
            your network name, security type and password in the standard <code class="rounded bg-neutral-100 px-1 font-mono text-xs dark:bg-neutral-800">WIFI:</code>
            format that iOS and Android cameras understand natively. One scan, one tap, connected.
          </p>
          <p>
            Everything happens locally: the code is generated by our open-source encoder running in your browser, and the
            password field is excluded from share links at the schema level — it cannot end up in a URL even by accident.
          </p>
        </div>
      </section>

      <FaqSection :items="faq" class="rounded-2xl bg-muted/50 p-6 sm:p-8" />
    </div>
  </div>
</template>
